Repository BibimMandu-IssueTacker/issue-tracker, pull requests merged in 2023-08, with the labels that each got.

#29 [BE] test/#28: 이슈 생성 테스트 로직 추가
  BE/src/test/java/com/issuetracker/acceptance/IssueAcceptanceTest.java
  BE/src/test/java/com/issuetracker/unit/AssigneeRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/IssueLabelMappingRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/IssueMapperTest.java
  BE/src/test/java/com/issuetracker/unit/IssueRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/LabelRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/MemberRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/MilestoneRepositoryTest.java
  BE/src/test/java/com/issuetracker/util/DatabaseInitialization.java
  BE/src/test/java/com/issuetracker/util/RepositoryTest.java
  BE/src/test/java/com/issuetracker/util/fixture/AssigneeFixture.java
  BE/src/test/java/com/issuetracker/util/fixture/IssueCommentFixture.java
  BE/src/test/java/com/issuetracker/util/fixture/IssueFixture.java
  BE/src/test/java/com/issuetracker/util/fixture/IssueLabelMappingFixture.java
  BE/src/test/java/com/issuetracker/util/fixture/LabelFixture.java
  BE/src/test/java/com/issuetracker/util/fixture/MemberFixture.java
  BE/src/test/java/com/issuetracker/util/fixture/MilestoneFixture.java
Labels: BE, test, SPRINT#2

#30 test/#28: validator 테스트 로직 추가
  BE/src/main/java/com/issuetracker/issue/application/IssueCreator.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueCreateInputData.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/AssigneeRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/IssueLabelMappingRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueCreateRequest.java
  BE/src/main/java/com/issuetracker/label/application/LabelValidator.java
  BE/src/main/java/com/issuetracker/member/application/MemberValidator.java
  BE/src/main/java/com/issuetracker/milestone/application/MilestoneValidator.java
  BE/src/test/java/com/issuetracker/unit/repository/AssigneeRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/repository/IssueLabelMappingRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/repository/IssueMapperTest.java
  BE/src/test/java/com/issuetracker/unit/repository/IssueRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/repository/LabelRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/repository/MemberRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/repository/MilestoneRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/validator/LabelValidatorTest.java
  BE/src/test/java/com/issuetracker/unit/validator/MemberValidatorTest.java
  BE/src/test/java/com/issuetracker/unit/validator/MilestoneValidatorTest.java
  BE/src/test/java/com/issuetracker/util/MockTest.java
  BE/src/test/resources/shema.sql
Labels: BE, test

#32 [BE] test/#28: 이슈 생성 테스트 로직 추가
  BE/src/main/java/com/issuetracker/issue/application/IssueCreator.java
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueCreateInputData.java
  BE/src/main/java/com/issuetracker/issue/domain/IssueMapper.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/AssigneeRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/IssueLabelMappingRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/IssueRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueCreateRequest.java
  BE/src/main/java/com/issuetracker/label/application/LabelValidator.java
  BE/src/main/java/com/issuetracker/label/infrastructure/LabelRepository.java
  BE/src/main/java/com/issuetracker/member/application/MemberValidator.java
  BE/src/main/java/com/issuetracker/member/infrastructure/MemberRepository.java
  BE/src/main/java/com/issuetracker/milestone/application/MilestoneValidator.java
  BE/src/test/java/com/issuetracker/unit/IssueCreatorTest.java
  BE/src/test/java/com/issuetracker/unit/repository/AssigneeRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/repository/IssueLabelMappingRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/repository/IssueMapperTest.java
  BE/src/test/java/com/issuetracker/unit/repository/IssueRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/repository/LabelRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/repository/MemberRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/repository/MilestoneRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/validator/LabelValidatorTest.java
  BE/src/test/java/com/issuetracker/unit/validator/MemberValidatorTest.java
  BE/src/test/java/com/issuetracker/unit/validator/MilestoneValidatorTest.java
  BE/src/test/java/com/issuetracker/util/MockTest.java
  BE/src/test/resources/shema.sql
Labels: BE, test, SPRINT#2

#33 [BE] test/#28: 이슈 생성 테스트 로직 추가
  BE/src/main/java/com/issuetracker/issue/application/IssueCreator.java
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/domain/IssueMapper.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/IssueRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueCreateRequest.java
  BE/src/main/java/com/issuetracker/label/application/LabelValidator.java
  BE/src/main/java/com/issuetracker/label/infrastructure/LabelRepository.java
  BE/src/main/java/com/issuetracker/member/application/MemberValidator.java
  BE/src/main/java/com/issuetracker/member/infrastructure/MemberRepository.java
  BE/src/test/java/com/issuetracker/unit/IssueCreatorTest.java
  BE/src/test/java/com/issuetracker/unit/repository/IssueMapperTest.java
  BE/src/test/java/com/issuetracker/unit/validator/LabelValidatorTest.java
  BE/src/test/java/com/issuetracker/unit/validator/MemberValidatorTest.java
Labels: BE, test, SPRINT#2

#35 [Be] chore/#34 CI/CD 기능 추가
  .github/workflows/auto-deploy.yml
  BE/src/main/java/com/issuetracker/config/WebConfig.java
  BE/src/main/resources/application-testDB.yml
  BE/src/test/java/com/issuetracker/IssueTrackerApplicationTests.java
  BE/src/test/resources/shema.sql
  appspec.yml
  deploy.sh
Labels: BE, chore

#40 [BE] feat/#38: 담당자 목록 조회하는 API 구현
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/dto/AssigneeInformation.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/AssigneeRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/AssigneeResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/AssigneesResponse.java
  BE/src/test/java/com/issuetracker/acceptance/IssueAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/IssueSteps.java
  BE/src/test/java/com/issuetracker/unit/repository/AssigneeRepositoryTest.java
Labels: BE, feat, SPRINT#2

#41 [BE] feat/#39: 이슈에 등록 되어있는 라벨 목록 조회하는 API 구현
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueAssigneeInformation.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueLabelMappingInformation.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/AssigneeRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/IssueLabelMappingRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/AssigneeResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/AssigneesResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueAssigneeResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueAssigneesResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueLabelMappingResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueLabelMappingsResponse.java
  BE/src/test/java/com/issuetracker/acceptance/IssueAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/IssueSteps.java
  BE/src/test/java/com/issuetracker/unit/repository/IssueLabelMappingRepositoryTest.java
Labels: BE, feat, SPRINT#2

#42 [BE] feat/#37: 필터용 작성자 목록 반환 API 개발
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/dto/AuthorSearchInformation.java
  BE/src/main/java/com/issuetracker/issue/domain/Author.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/AuthorRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/AuthorSearchResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/AuthorsSearchResponse.java
  BE/src/test/java/com/issuetracker/acceptance/IssueAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/IssueSteps.java
Labels: BE, feat, test, SPRINT#2

#45 fix/#44: 이슈 목록 조회 시 마일스톤이 null 일 경우 500 ERROR 수정
  BE/src/main/java/com/issuetracker/issue/application/IssueCreator.java
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueCreateInputData.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueSearchInformation.java
  BE/src/main/java/com/issuetracker/issue/domain/Issue.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueSearchResponse.java
  BE/src/main/java/com/issuetracker/milestone/application/MilestoneValidator.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneSearchInformation.java
  BE/src/main/java/com/issuetracker/milestone/domain/Milestone.java
  BE/src/main/java/com/issuetracker/milestone/infrastructure/MilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneSearchResponse.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestonesSearchResponse.java
  BE/src/test/java/com/issuetracker/acceptance/IssueAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/IssueSteps.java
  BE/src/test/java/com/issuetracker/unit/IssueCreatorTest.java
  BE/src/test/java/com/issuetracker/unit/repository/IssueRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/repository/MilestoneRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/validator/MilestoneValidatorTest.java
Labels: BE, fix

#51 [FE] feat/#50: 리액트 라우터 추가
  FE/.gitignore
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
Labels: FE, feat, SPRINT#2

#52 [FE] refactor/#47: 메인페이지 리팩토링
  FE/src/components/Button/Button.tsx
  FE/src/components/Button/ButtonStyle.ts
  FE/src/components/DropdownIndicator/DropdownIndicator.tsx
  FE/src/components/FilterBar/FilterBar.tsx
  FE/src/components/Header/Header.tsx
  FE/src/components/Input/Input.tsx
  FE/src/components/IssueList/IssueList.tsx
  FE/src/pages/MainPage.tsx
Labels: FE, refactor, SPRINT#2

#54 [FE] feat/#53: 2주차 공용 컴포넌트 구현
  FE/src/components/Alert/Alert.tsx
  FE/src/components/DropdownPanel/DropdownItem.tsx
  FE/src/components/DropdownPanel/DropdownPanel.tsx
  FE/src/components/ProgressBar/ProgressBar.tsx
  FE/src/components/ProgressIndicator/ProgressIndicator.tsx
  FE/src/components/SideBar/AssigneeItem.tsx
  FE/src/components/SideBar/LabelItem.tsx
  FE/src/components/SideBar/MilestonesItem.tsx
  FE/src/components/SideBar/SideBar.tsx
  FE/src/components/SideBar/SideBarList.tsx
  FE/src/components/UserProfileButton/UserProfileButton.tsx
  FE/src/components/common/Button/Button.tsx
  FE/src/components/common/Button/ButtonStyle.ts
  FE/src/components/common/Input/Input.tsx
  FE/src/components/common/TextInput/TextInput.tsx
Labels: FE, feat, SPRINT#2

#56 [BE] feat/#49: 이슈 목록 조회 API 수정
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueSearchInformation.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssuesCountInformation.java
  BE/src/main/java/com/issuetracker/issue/domain/IssuesCountData.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/IssueRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssuesCountResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssuesSearchResponse.java
  BE/src/test/java/com/issuetracker/acceptance/IssueAcceptanceTest.java
  BE/src/test/java/com/issuetracker/unit/repository/IssueRepositoryTest.java
Labels: BE, feat, SPRINT#2

#57 [FE] feat/#46: 이슈 생성 페이지 구현
  FE/src/pages/AddIssuePage.tsx
  FE/src/type.tsx
Labels: FE, feat, SPRINT#2

#64 [FE] feat/#48: 이슈 목록 페이지 필터 기능 구현
  FE/src/pages/MainPage.tsx
  FE/src/utils/parseFilter.ts
  FE/src/utils/parseParam.ts
Labels: FE, feat, SPRINT#2

#68 [FE] refactor/#67: 2주차 컴포넌트 리팩토링
  FE/src/components/DropdownIndicator/DropdownIndicator.tsx
  FE/src/components/DropdownPanel/DropdownItem.tsx
  FE/src/components/DropdownPanel/DropdownPanel.tsx
  FE/src/components/FilterBar/FilterBar.tsx
  FE/src/components/Header/Header.tsx
  FE/src/components/common/Button/Button.tsx
  FE/src/components/common/Input/Input.tsx
  FE/src/components/common/TextInput/TextInput.tsx
  FE/src/pages/AddIssuePage.tsx
  FE/src/type.tsx
Labels: FE, refactor, SPRINT#2

#69 [DEV] FE 이슈 목록 페이지 필터 기능
  FE/src/App.tsx
  FE/src/components/DropdownIndicator/DropdownIndicator.tsx
  FE/src/components/DropdownPanel/DropdownItem.tsx
  FE/src/components/DropdownPanel/DropdownPanel.tsx
  FE/src/components/FilterBar/FilterBar.tsx
  FE/src/components/Header/Header.tsx
  FE/src/components/common/Button/Button.tsx
  FE/src/components/common/Input/Input.tsx
  FE/src/components/common/TextInput/TextInput.tsx
  FE/src/pages/AddIssuePage.tsx
  FE/src/pages/LoginPage.tsx
  FE/src/pages/MainPage.tsx
  FE/src/type.tsx
  FE/src/utils/parseFilter.ts
  FE/src/utils/parseParam.ts
Labels: FE, feat, SPRINT#2

#72 [FE] fix/#71: 사이드바 드롭다운 인디케이터 오류 수정
  FE/src/components/SideBar/SideBar.tsx
  FE/src/components/SideBar/SideBarList.tsx
Labels: FE, fix, SPRINT#2

#76 [Be] 이슈 목록 조회 및 생성 버그 수정
  BE/src/main/java/com/issuetracker/config/GlobalExceptionHandler.java
  BE/src/main/java/com/issuetracker/config/IssueSearchArgumentResolver.java
  BE/src/main/java/com/issuetracker/config/WebConfig.java
  BE/src/main/java/com/issuetracker/config/exception/QueryStringKeyNotMatchException.java
  BE/src/main/java/com/issuetracker/issue/application/IssueCreator.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueCreateInputData.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueCreateRequest.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueSearchRequest.java
  BE/src/main/java/com/issuetracker/label/application/LabelValidator.java
  BE/src/main/java/com/issuetracker/member/application/MemberValidator.java
  BE/src/main/resources/mapper/IssueMapper.xml
  BE/src/test/java/com/issuetracker/acceptance/IssueAcceptanceTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/IssueMapperTest.java
  BE/src/test/java/com/issuetracker/util/steps/IssueSteps.java
Labels: BE, fix

#86 [BE] feat/#84: 라벨 생성 API 추가
  BE/src/main/java/com/issuetracker/config/GlobalExceptionHandler.java
  BE/src/main/java/com/issuetracker/label/application/LabelService.java
  BE/src/main/java/com/issuetracker/label/application/dto/LabelCreateInformation.java
  BE/src/main/java/com/issuetracker/label/application/dto/LabelCreateInputData.java
  BE/src/main/java/com/issuetracker/label/domain/LabelRepository.java
  BE/src/main/java/com/issuetracker/label/infrastructure/JdbcLabelRepository.java
  BE/src/main/java/com/issuetracker/label/ui/LabelController.java
  BE/src/main/java/com/issuetracker/label/ui/dto/LabelCreateRequest.java
  BE/src/main/java/com/issuetracker/label/ui/dto/LabelCreateResponse.java
Labels: BE, feat, SPRINT#3

#99 [BE] feat/#90: 이미지 업로드 기능 추가
  .github/workflows/auto-deploy.yml
  BE/build.gradle
  BE/src/main/java/com/issuetracker/config/ErrorResponse.java
  BE/src/main/java/com/issuetracker/config/GlobalExceptionHandler.java
  BE/src/main/java/com/issuetracker/config/exception/AwsS3Config.java
  BE/src/main/java/com/issuetracker/config/exception/ErrorType.java
  BE/src/main/java/com/issuetracker/file/application/FileService.java
  BE/src/main/java/com/issuetracker/file/application/dto/FileInformation.java
  BE/src/main/java/com/issuetracker/file/doamin/FileUpload.java
  BE/src/main/java/com/issuetracker/file/doamin/ImageFileDetail.java
  BE/src/main/java/com/issuetracker/file/infrastrucure/AmazonS3Upload.java
  BE/src/main/java/com/issuetracker/file/ui/FileController.java
  BE/src/main/java/com/issuetracker/file/ui/dto/FileResponse.java
  BE/src/main/java/com/issuetracker/label/application/dto/LabelCreateInputData.java
  BE/src/main/resources/application.yml
Labels: BE, feat, SPRINT#3

#104 [Be] feat/#100 이슈 수정 API
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/IssueValidator.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueSearchInformation.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueUpdateData.java
  BE/src/main/java/com/issuetracker/issue/domain/IssueRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/JdbcIssueRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueSearchResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueUpdateRequest.java
  BE/src/main/java/com/issuetracker/label/application/dto/LabelSearchInformation.java
  BE/src/main/java/com/issuetracker/label/ui/dto/LabelSearchResponse.java
  BE/src/test/java/com/issuetracker/acceptance/IssueAcceptanceTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/IssueMapperTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/IssueRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/validator/IssueValidatorTest.java
  BE/src/test/java/com/issuetracker/util/steps/IssueSteps.java
Labels: BE, feat, SPRINT#3

#108 [BE] feat/#107: 이슈 삭제하는 기능 추가
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/IssueValidator.java
  BE/src/main/java/com/issuetracker/issue/domain/IssueRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/JdbcIssueRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/test/java/com/issuetracker/acceptance/IssueAcceptanceTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/IssueRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/validator/IssueValidatorTest.java
  BE/src/test/java/com/issuetracker/util/steps/IssueSteps.java
Labels: BE, feat, SPRINT#3

#93 [BE] feat/#89 레이블 삭제 API 개발
  BE/src/main/java/com/issuetracker/config/exception/ErrorType.java
  BE/src/main/java/com/issuetracker/label/application/LabelService.java
  BE/src/main/java/com/issuetracker/label/application/dto/LabelDeleteInputData.java
  BE/src/main/java/com/issuetracker/label/domain/LabelRepository.java
  BE/src/main/java/com/issuetracker/label/infrastructure/JdbcLabelRepository.java
  BE/src/main/java/com/issuetracker/label/ui/LabelController.java
  BE/src/main/java/com/issuetracker/label/ui/dto/LabelDeleteRequest.java
Labels: BE, feat, SPRINT#3

#94 [BE] feat/#87 라벨 목록 불러오기 API 개발
  BE/src/main/java/com/issuetracker/label/application/LabelService.java
  BE/src/main/java/com/issuetracker/label/domain/LabelRepository.java
  BE/src/main/java/com/issuetracker/label/infrastructure/JdbcLabelRepository.java
  BE/src/main/java/com/issuetracker/label/ui/LabelController.java
Labels: BE, feat, SPRINT#3

#102 [BE] feat/#96 마일스톤 목록 반환 API 개발
  BE/src/main/java/com/issuetracker/label/ui/dto/LabelsResponse.java
  BE/src/main/java/com/issuetracker/milestone/application/MilestoneService.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneInformation.java
  BE/src/main/java/com/issuetracker/milestone/domain/Milestone.java
  BE/src/main/java/com/issuetracker/milestone/domain/MilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/infrastructure/JdbcMilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/ui/MilestoneController.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneResponse.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestonesResponse.java
Labels: BE, feat, SPRINT#3

#103 [BE] feat/#97 마일스톤 수정
  BE/src/main/java/com/issuetracker/milestone/application/MilestoneService.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneUpdateInputData.java
  BE/src/main/java/com/issuetracker/milestone/domain/MilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/infrastructure/JdbcMilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/ui/MilestoneController.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneUpdateRequest.java
Labels: BE, feat, SPRINT#3

#106 [BE] feat/#98 마일스톤 삭제 API 개발
  BE/src/main/java/com/issuetracker/milestone/application/MilestoneService.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneDeleteInputData.java
  BE/src/main/java/com/issuetracker/milestone/domain/MilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/infrastructure/JdbcMilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/ui/MilestoneController.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneDeleteRequest.java
Labels: BE, feat, SPRINT#3

#111 [BE] feat/#105 마일스톤 open/clode 상태 변경 API 추가
  BE/src/main/java/com/issuetracker/config/GlobalExceptionHandler.java
  BE/src/main/java/com/issuetracker/config/exception/ErrorType.java
  BE/src/main/java/com/issuetracker/milestone/application/MilestoneService.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneUpdateOpenStatusInputData.java
  BE/src/main/java/com/issuetracker/milestone/domain/MilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/infrastructure/JdbcMilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/ui/MilestoneController.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneUpdateOpenStatusRequest.java
Labels: BE, feat, SPRINT#3

#112 feat/#82: 이슈 수정용 담당자 목록 반환 API 추가
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/dto/AssigneesForIssueUpdateInformation.java
  BE/src/main/java/com/issuetracker/issue/domain/AssigneeRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/JdbcAssigneeRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/AssigneesForIssueUpdateResponse.java
Labels: BE, feat, SPRINT#3

#113 [BE] feat/#83: 이슈 수정용 레이블 목록 반환 API 추가
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/dto/LabelsForIssueUpdateInformation.java
  BE/src/main/java/com/issuetracker/issue/domain/AssignedLabelRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/JdbcAssignedLabelRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/LabelsForIssueUpdateResponse.java
Labels: BE, feat, SPRINT#3

#115 [BE] refactor/#114: 이슈 수정용 레이블, 마일스톤 목록 반환 부분 네이밍 변경
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/dto/AssigneeCandidatesInformation.java
  BE/src/main/java/com/issuetracker/issue/application/dto/LabelCandidatesInformation.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/AssigneeCandidatesResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/AssigneesForIssueUpdateResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/LabelCandidatesResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/LabelsForIssueUpdateResponse.java
Labels: FE, BE, SPRINT#3

#118 [Be] feat/#117 이슈에 담당자 등록/삭제 기능
  BE/src/main/java/com/issuetracker/config/exception/ErrorType.java
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/IssueValidator.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueCreateInputData.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueDetailInformation.java
  BE/src/main/java/com/issuetracker/issue/application/dto/assignedlabel/AssignedLabelCandidatesInformation.java
  BE/src/main/java/com/issuetracker/issue/application/dto/assignee/AssigneeCandidatesInformation.java
  BE/src/main/java/com/issuetracker/issue/application/dto/assignee/AssigneeCreateData.java
  BE/src/main/java/com/issuetracker/issue/application/dto/comment/IssueCommentCreateData.java
  BE/src/main/java/com/issuetracker/issue/application/dto/comment/IssueCommentCreateInformation.java
  BE/src/main/java/com/issuetracker/issue/application/dto/comment/IssueCommentInformation.java
  BE/src/main/java/com/issuetracker/issue/application/dto/comment/IssueCommentUpdateData.java
  BE/src/main/java/com/issuetracker/issue/domain/IssueDetailRead.java
  BE/src/main/java/com/issuetracker/issue/domain/assignedlabel/AssignedLabel.java
  BE/src/main/java/com/issuetracker/issue/domain/assignedlabel/AssignedLabelRepository.java
  BE/src/main/java/com/issuetracker/issue/domain/assignee/Assignee.java
  BE/src/main/java/com/issuetracker/issue/domain/assignee/AssigneeRepository.java
  BE/src/main/java/com/issuetracker/issue/domain/comment/IssueComment.java
  BE/src/main/java/com/issuetracker/issue/domain/comment/IssueCommentRead.java
  BE/src/main/java/com/issuetracker/issue/domain/comment/IssueCommentRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/JdbcAssignedLabelRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/JdbcAssigneeRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/JdbcIssueCommentRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueDetailResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/LabelCandidatesResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/assignedlabel/AssignedLabelCandidatesResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/assignedlabel/AssignedLabelResponses.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/assignee/AssigneeCandidatesResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/assignee/AssigneeCreateRequest.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/assignee/AssigneesResponses.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/assignee/AuthorResponses.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/comment/IssueCommentCreateRequest.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/comment/IssueCommentCreateResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/comment/IssueCommentResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/comment/IssueCommentUpdateRequest.java
  BE/src/main/java/com/issuetracker/member/domain/Member.java
  BE/src/main/resources/mapper/IssueMapper.xml
  BE/src/test/java/com/issuetracker/acceptance/IssueAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/IssueCommentAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/IssueFilterAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/IssueOtherAcceptanceTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/AssignedLabelRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/AssigneeRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/IssueCommentRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/validator/IssueValidatorTest.java
  BE/src/test/java/com/issuetracker/util/steps/IssueSteps.java
Labels: BE, feat, SPRINT#3

#120 [BE] feat/#119 이슈에 라벨 등록 / 삭제 기능
  BE/src/main/java/com/issuetracker/config/exception/ErrorType.java
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/IssueValidator.java
  BE/src/main/java/com/issuetracker/issue/application/dto/assignedlabel/AssignedLabelCreateData.java
  BE/src/main/java/com/issuetracker/issue/application/dto/assignedlabel/AssignedLabelInformation.java
  BE/src/main/java/com/issuetracker/issue/application/dto/assignee/AssigneeCreateInformation.java
  BE/src/main/java/com/issuetracker/issue/domain/assignedlabel/AssignedLabelRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/JdbcAssignedLabelRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/assignedlabel/AssignedLabelCreateRequest.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/assignedlabel/AssignedLabelCreateResponse.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/assignee/AssigneesCreateResponse.java
  BE/src/main/java/com/issuetracker/label/application/LabelValidator.java
  BE/src/main/java/com/issuetracker/label/domain/Label.java
  BE/src/main/java/com/issuetracker/label/domain/LabelRepository.java
  BE/src/main/java/com/issuetracker/label/infrastructure/JdbcLabelRepository.java
  BE/src/test/java/com/issuetracker/acceptance/IssueCommentAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/IssueOtherAcceptanceTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/AssignedLabelRepositoryTest.java
  BE/src/test/java/com/issuetracker/util/steps/IssueSteps.java
Labels: BE, feat, SPRINT#3

#126 feat/#125: 마일스톤 목록 반환시 isOpen필드 추가
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneCandidatesInformation.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneInformation.java
  BE/src/main/java/com/issuetracker/milestone/infrastructure/JdbcMilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneResponse.java
Labels: BE, feat, SPRINT#3

#127 [BE] test/#114 레이블, 마일스톤 CRUD 테스트 추가
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneResponse.java
  BE/src/test/java/com/issuetracker/acceptance/LabelAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/MilestoneAcceptanceTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/LabelRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/MilestoneRepositoryTest.java
  BE/src/test/java/com/issuetracker/util/steps/LabelSteps.java
  BE/src/test/java/com/issuetracker/util/steps/MilestoneSteps.java
Labels: BE, feat, SPRINT#3

#131 [BE] fix/#128 버그 수정
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneUpdateInputData.java
  BE/src/main/java/com/issuetracker/milestone/infrastructure/JdbcMilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneCreateRequest.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneResponse.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneUpdateRequest.java
  BE/src/test/java/com/issuetracker/acceptance/MilestoneAcceptanceTest.java
Labels: BE, feat, SPRINT#3

#135 [BE] fix/#134 version v.0.3.1 버그 수정
  BE/src/main/java/com/issuetracker/config/WebConfig.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/JdbcAssignedLabelRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/JdbcIssueRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueCreateRequest.java
  BE/src/main/java/com/issuetracker/label/infrastructure/JdbcLabelRepository.java
  BE/src/main/java/com/issuetracker/milestone/infrastructure/JdbcMilestoneRepository.java
  BE/src/test/java/com/issuetracker/acceptance/IssueAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/LabelAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/MilestoneAcceptanceTest.java
Labels: BE, fix

#137 [BE] fix/#136: 이슈 상세 조회 시 댓글 생성 날짜 null인 현상 수정
  BE/build.gradle
  BE/src/main/resources/mapper/IssueMapper.xml
Labels: BE, fix, SPRINT#3

#138 Be fix/#128 fix
  BE/src/main/java/com/issuetracker/label/application/LabelService.java
  BE/src/main/java/com/issuetracker/label/application/dto/LabelCountMetadataInformation.java
  BE/src/main/java/com/issuetracker/label/application/dto/LabelsInformation.java
  BE/src/main/java/com/issuetracker/label/domain/LabelCountMetadata.java
  BE/src/main/java/com/issuetracker/label/domain/LabelRepository.java
  BE/src/main/java/com/issuetracker/label/infrastructure/JdbcLabelRepository.java
  BE/src/main/java/com/issuetracker/label/ui/dto/LabelCountMetadataResponse.java
  BE/src/main/java/com/issuetracker/label/ui/dto/LabelsResponse.java
  BE/src/main/java/com/issuetracker/milestone/application/MilestoneService.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/IssueDetailMilestoneInformation.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneCountMetadataInformation.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneInformation.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneSearchByOpenStatusInputData.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestonesInformation.java
  BE/src/main/java/com/issuetracker/milestone/domain/Milestone.java
  BE/src/main/java/com/issuetracker/milestone/domain/MilestoneCountMetadata.java
  BE/src/main/java/com/issuetracker/milestone/domain/MilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/infrastructure/JdbcMilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/ui/MilestoneController.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/IssueDetailMilestoneResponse.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneCountMetadataResponse.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneResponse.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneSearchByOpenStatusRequest.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestonesResponse.java
  BE/src/test/java/com/issuetracker/acceptance/MilestoneAcceptanceTest.java
  BE/src/test/java/com/issuetracker/util/steps/MilestoneSteps.java
Labels: BE, feat, SPRINT#3

#140 fix/#139: dev-be 통합시 발생한 SQL문 에러 수정
  BE/src/main/java/com/issuetracker/milestone/infrastructure/JdbcMilestoneRepository.java
  BE/src/test/java/com/issuetracker/acceptance/MilestoneAcceptanceTest.java
Labels: BE, fix, SPRINT#3

#143 [FE] refactor/#46: 이슈 추가 페이지 리팩토링
  FE/src/pages/AddIssuePage.tsx
  FE/src/type.tsx
Labels: FE, feat, SPRINT#3

#144 [DEV] BE version 0.3.1 버그 수정
  BE/build.gradle
  BE/src/main/java/com/issuetracker/config/WebConfig.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/JdbcAssignedLabelRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/JdbcIssueRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueCreateRequest.java
  BE/src/main/java/com/issuetracker/label/application/LabelService.java
  BE/src/main/java/com/issuetracker/label/application/dto/LabelCountMetadataInformation.java
  BE/src/main/java/com/issuetracker/label/application/dto/LabelsInformation.java
  BE/src/main/java/com/issuetracker/label/domain/LabelCountMetadata.java
  BE/src/main/java/com/issuetracker/label/domain/LabelRepository.java
  BE/src/main/java/com/issuetracker/label/infrastructure/JdbcLabelRepository.java
  BE/src/main/java/com/issuetracker/label/ui/dto/LabelCountMetadataResponse.java
  BE/src/main/java/com/issuetracker/label/ui/dto/LabelsResponse.java
  BE/src/main/java/com/issuetracker/milestone/application/MilestoneService.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/IssueDetailMilestoneInformation.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneCountMetadataInformation.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneInformation.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneSearchByOpenStatusInputData.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestonesInformation.java
  BE/src/main/java/com/issuetracker/milestone/domain/Milestone.java
  BE/src/main/java/com/issuetracker/milestone/domain/MilestoneCountMetadata.java
  BE/src/main/java/com/issuetracker/milestone/domain/MilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/infrastructure/JdbcMilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/ui/MilestoneController.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/IssueDetailMilestoneResponse.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneCountMetadataResponse.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneResponse.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneSearchByOpenStatusRequest.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestonesResponse.java
  BE/src/main/resources/mapper/IssueMapper.xml
  BE/src/test/java/com/issuetracker/acceptance/IssueAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/LabelAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/MilestoneAcceptanceTest.java
  BE/src/test/java/com/issuetracker/util/steps/MilestoneSteps.java
Labels: BE, fix, SPRINT#3

#152 [BE]fix/#151 이슈 목록 조회 시 isOpen이 null일 경우 전체 조회가 안되는 현상 수정
  BE/src/main/java/com/issuetracker/config/IssueSearchArgumentResolver.java
  BE/src/main/java/com/issuetracker/config/WebConfig.java
Labels: BE, fix, SPRINT#3

#154 [BE] feat/#153: 마일스톤 목록 반환 시 issue 개수 반환하도록 변경
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneCandidatesInformation.java
  BE/src/main/java/com/issuetracker/milestone/application/dto/MilestoneInformation.java
  BE/src/main/java/com/issuetracker/milestone/domain/Milestone.java
  BE/src/main/java/com/issuetracker/milestone/infrastructure/JdbcMilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneResponse.java
Labels: BE, feat, SPRINT#3

#170 [BE] fix/#169: s3 image upload 수정
  BE/build.gradle
  BE/src/main/java/com/issuetracker/config/exception/AwsS3Config.java
  BE/src/main/java/com/issuetracker/file/application/FileService.java
  BE/src/main/java/com/issuetracker/file/application/dto/FileInformation.java
  BE/src/main/java/com/issuetracker/file/application/dto/FileMetadata.java
  BE/src/main/java/com/issuetracker/file/doamin/ImageFileDetail.java
  BE/src/main/java/com/issuetracker/file/infrastrucure/AmazonS3Upload.java
  BE/src/main/java/com/issuetracker/file/ui/dto/FileResponse.java
  BE/src/main/resources/application.yml
Labels: BE, fix, SPRINT#4

#172 feat/#171: 이슈 open/close 일괄 변경 기능 추가
  BE/src/main/java/com/issuetracker/common/config/ErrorResponse.java
  BE/src/main/java/com/issuetracker/common/config/GlobalExceptionHandler.java
  BE/src/main/java/com/issuetracker/common/config/IssueSearchArgumentResolver.java
  BE/src/main/java/com/issuetracker/common/config/WebConfig.java
  BE/src/main/java/com/issuetracker/common/config/exception/CustomHttpException.java
  BE/src/main/java/com/issuetracker/common/config/exception/ErrorType.java
  BE/src/main/java/com/issuetracker/common/util/ConvertorUtil.java
  BE/src/main/java/com/issuetracker/file/doamin/ImageFileDetail.java
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/IssueValidator.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueUpdateAllOpenData.java
  BE/src/main/java/com/issuetracker/issue/domain/IssueRepository.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/JdbcIssueRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueCreateRequest.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueUpdateAllOpenRequest.java
  BE/src/main/java/com/issuetracker/label/application/LabelService.java
  BE/src/main/java/com/issuetracker/label/application/LabelValidator.java
  BE/src/main/java/com/issuetracker/label/ui/dto/LabelDeleteRequest.java
  BE/src/main/java/com/issuetracker/member/application/MemberValidator.java
  BE/src/main/java/com/issuetracker/milestone/application/MilestoneService.java
  BE/src/main/java/com/issuetracker/milestone/application/MilestoneValidator.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneDeleteRequest.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneSearchByOpenStatusRequest.java
  BE/src/main/java/com/issuetracker/milestone/ui/dto/MilestoneUpdateOpenStatusRequest.java
  BE/src/test/java/com/issuetracker/acceptance/IssueAcceptanceTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/IssueRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/validator/IssueValidatorTest.java
  BE/src/test/java/com/issuetracker/unit/validator/LabelValidatorTest.java
  BE/src/test/java/com/issuetracker/unit/validator/MemberValidatorTest.java
  BE/src/test/java/com/issuetracker/unit/validator/MilestoneValidatorTest.java
  BE/src/test/java/com/issuetracker/util/steps/IssueSteps.java
Labels: BE, feat, SPRINT#4

#174 [BE] feat/#173 회원 정보 조회/수정 하는 기능 추가
  BE/src/main/java/com/issuetracker/member/application/MemberService.java
  BE/src/main/java/com/issuetracker/member/application/dto/MemberUpdateData.java
  BE/src/main/java/com/issuetracker/member/domain/MemberRepository.java
  BE/src/main/java/com/issuetracker/member/infrastructure/JdbcMemberRepository.java
  BE/src/main/java/com/issuetracker/member/ui/MemberController.java
  BE/src/main/java/com/issuetracker/member/ui/dto/MemberUpdateRequest.java
  BE/src/test/java/com/issuetracker/acceptance/MemberAcceptanceTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/MemberRepositoryTest.java
  BE/src/test/java/com/issuetracker/util/steps/MemberSteps.java
  BE/src/test/resources/bike.jpg
Labels: BE, feat, SPRINT#4

#177 [BE] refactor/#175 code refactor
  .github/workflows/auto-deploy.yml
  BE/build.gradle
  BE/src/main/java/com/issuetracker/common/config/IssueSearchArgumentResolver.java
  BE/src/main/java/com/issuetracker/common/config/exception/ErrorType.java
  BE/src/main/java/com/issuetracker/common/util/ConvertorUtil.java
  BE/src/main/java/com/issuetracker/issue/application/AssignedLabelService.java
  BE/src/main/java/com/issuetracker/issue/application/AssigneeService.java
  BE/src/main/java/com/issuetracker/issue/application/IssueCommentService.java
  BE/src/main/java/com/issuetracker/issue/application/IssueService.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueSearchInformation.java
  BE/src/main/java/com/issuetracker/issue/application/dto/IssueSearchInputData.java
  BE/src/main/java/com/issuetracker/issue/domain/IssueRead.java
  BE/src/main/java/com/issuetracker/issue/domain/IssueSearch.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueSearchRequest.java
  BE/src/main/java/com/issuetracker/issue/ui/dto/IssueSearchResponse.java
  BE/src/main/java/com/issuetracker/label/application/LabelService.java
  BE/src/main/java/com/issuetracker/label/application/LabelValidator.java
  BE/src/main/java/com/issuetracker/label/domain/LabelRepository.java
  BE/src/main/java/com/issuetracker/label/infrastructure/JdbcLabelRepository.java
  BE/src/main/java/com/issuetracker/milestone/application/MilestoneService.java
  BE/src/main/java/com/issuetracker/milestone/application/MilestoneValidator.java
  BE/src/main/java/com/issuetracker/milestone/domain/MilestoneRepository.java
  BE/src/main/java/com/issuetracker/milestone/infrastructure/JdbcMilestoneRepository.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/mapper/IssueMapper.xml
  BE/src/test/java/com/issuetracker/acceptance/AssignedLabelAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/AssigneeAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/IssueAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/IssueOtherAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/LabelAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/MilestoneAcceptanceTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/AssignedLabelJdbcRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/AssigneeJdbcRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/IssueCommentJdbcRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/IssueJdbcRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/IssueMapperTestJdbc.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/LabelJdbcRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/MemberJdbcRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/MilestoneJdbcRepositoryTest.java
  BE/src/test/java/com/issuetracker/util/AcceptanceTest.java
  BE/src/test/java/com/issuetracker/util/DatabaseLoader.java
  BE/src/test/java/com/issuetracker/util/JdbcRepositoryTest.java
  BE/src/test/java/com/issuetracker/util/MyBatisMapperTest.java
  BE/src/test/java/com/issuetracker/util/MyBatisRepositoryTest.java
  BE/src/test/java/com/issuetracker/util/MySqlContainer.java
  BE/src/test/java/com/issuetracker/util/fixture/LabelFixture.java
  BE/src/test/java/com/issuetracker/util/fixture/MemberFixture.java
  BE/src/test/java/com/issuetracker/util/fixture/MilestoneFixture.java
  BE/src/test/java/com/issuetracker/util/steps/AssignedLabelSteps.java
  BE/src/test/java/com/issuetracker/util/steps/AssigneeSteps.java
  BE/src/test/java/com/issuetracker/util/steps/IssueSteps.java
Labels: BE, refactor, SPRINT#4

#179 feat/#176: auto-deploy에 oauth.properties 생성 명령어 추가
  .github/workflows/auto-deploy.yml
Labels: BE, feat, SPRINT#4

#181 [BE] fix/#180 이슈 생성, 회원 정보 수정, 로깅 변경
  BE/src/main/java/com/issuetracker/common/config/ErrorResponse.java
  BE/src/main/java/com/issuetracker/common/config/GlobalExceptionHandler.java
  BE/src/main/java/com/issuetracker/common/config/exception/ErrorType.java
  BE/src/main/java/com/issuetracker/common/config/filter/JwtAuthorizationFilter.java
  BE/src/main/java/com/issuetracker/issue/application/dto/assignedlabel/AssignedLabelCandidatesInformation.java
  BE/src/main/java/com/issuetracker/issue/infrastrucure/JdbcAssignedLabelRepository.java
  BE/src/main/java/com/issuetracker/issue/ui/IssueController.java
  BE/src/main/java/com/issuetracker/label/application/LabelService.java
  BE/src/main/java/com/issuetracker/label/application/dto/LabelCreateInputData.java
  BE/src/main/java/com/issuetracker/label/application/dto/LabelInformation.java
  BE/src/main/java/com/issuetracker/label/application/dto/LabelUpdateInputData.java
  BE/src/main/java/com/issuetracker/label/domain/Label.java
  BE/src/main/java/com/issuetracker/label/domain/LabelRepository.java
  BE/src/main/java/com/issuetracker/label/infrastructure/JdbcLabelRepository.java
  BE/src/main/java/com/issuetracker/label/ui/dto/LabelCreateRequest.java
  BE/src/main/java/com/issuetracker/label/ui/dto/LabelResponse.java
  BE/src/main/java/com/issuetracker/label/ui/dto/LabelUpdateRequest.java
  BE/src/main/java/com/issuetracker/member/application/MemberService.java
  BE/src/main/java/com/issuetracker/member/application/dto/MemberUpdateData.java
  BE/src/main/java/com/issuetracker/member/domain/Member.java
  BE/src/main/java/com/issuetracker/member/infrastructure/JdbcMemberRepository.java
  BE/src/main/java/com/issuetracker/milestone/infrastructure/JdbcMilestoneRepository.java
  BE/src/main/resources/logback-spring.xml
  BE/src/main/resources/mapper/IssueMapper.xml
  BE/src/test/java/com/issuetracker/acceptance/AssignedLabelAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/LabelAcceptanceTest.java
  BE/src/test/java/com/issuetracker/acceptance/MemberAcceptanceTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/LabelJdbcRepositoryTest.java
  BE/src/test/java/com/issuetracker/unit/infrastrucure/MilestoneJdbcRepositoryTest.java
  BE/src/test/java/com/issuetracker/util/fixture/LabelFixture.java
  BE/src/test/resources/schema.sql
Labels: BE, fix, SPRINT#4

#187 [BE] 회원가입시 파일업로드 기능 추가
  BE/src/main/java/com/issuetracker/account/application/AccountService.java
  BE/src/main/java/com/issuetracker/account/application/dto/SignUpInputData.java
  BE/src/main/java/com/issuetracker/account/domain/AccountRepository.java
  BE/src/main/java/com/issuetracker/account/infrastructure/JdbcAccountRepository.java
  BE/src/main/java/com/issuetracker/account/ui/AccountController.java
  BE/src/main/java/com/issuetracker/account/ui/dto/SignupRequest.java
  BE/src/main/java/com/issuetracker/common/config/exception/ErrorType.java
Labels: BE, feat, SPRINT#4

#189 [BE] feat/#176: 디폴트 프로필 이미지 추가
  BE/src/main/java/com/issuetracker/account/application/AccountService.java
  BE/src/main/java/com/issuetracker/member/application/MemberService.java
  BE/src/test/resources/schema.sql
Labels: BE, feat, SPRINT#4
