Repository BibimMandu-IssueTacker/issue-tracker, pull requests merged in 2023-07, with the labels that each got.

#4 [FE] chore/#1: 개발 환경 초기 세팅
  FE/.eslintrc.cjs
  FE/.gitignore
  FE/.prettierrc
  FE/index.html
  FE/package-lock.json
  FE/package.json
  FE/public/icon/issue.png
  FE/src/App.tsx
  FE/src/main.tsx
  FE/src/styles/GlobalStyles.ts
  FE/src/styles/Theme.ts
  FE/src/vite-env.d.ts
  FE/tsconfig.json
  FE/tsconfig.node.json
  FE/vite.config.ts
Labels: FE, chore, SPRINT#1

#6 [FE] design/#5: 공용 CSS 스타일 구현
  FE/index.html
  FE/public/favicon/issue.png
  FE/public/icons/alertCircle.svg
  FE/public/icons/archive.svg
  FE/public/icons/calendar.svg
  FE/public/icons/checkBoxActive.svg
  FE/public/icons/checkBoxDisable.svg
  FE/public/icons/checkBoxInitial.svg
  FE/public/icons/checkOffCircle.svg
  FE/public/icons/checkOnCircle.svg
  FE/public/icons/chevronDown.svg
  FE/public/icons/edit.svg
  FE/public/icons/label.svg
  FE/public/icons/milestone.svg
  FE/public/icons/paperclip.svg
  FE/public/icons/plus.svg
  FE/public/icons/refreshCcw.svg
  FE/public/icons/search.svg
  FE/public/icons/smile.svg
  FE/public/icons/trash.svg
  FE/public/icons/userImageLarge.svg
  FE/public/icons/userImageSmall.svg
  FE/public/icons/xSquare.svg
  FE/src/styles/DesignSystem.ts
  FE/src/styles/GlobalStyles.ts
  FE/src/styles/Theme.ts
  FE/src/styles/base/Colors.ts
  FE/src/styles/base/Object.ts
  FE/src/styles/base/Typo.ts
Labels: FE, design, SPRINT#1

#8 [FE] feat/#7: 다크 모드 구현
  FE/src/App.tsx
  FE/src/hooks/useDarkMode.ts
Labels: FE, feat, SPRINT#1

#3 [BE] chore/#2: Spring Boot 프로젝트 세팅
  BE/app/.gitignore
  BE/app/build.gradle
  BE/app/gradle/wrapper/gradle-wrapper.jar
  BE/app/gradle/wrapper/gradle-wrapper.properties
  BE/app/gradlew
  BE/app/gradlew.bat
  BE/app/settings.gradle
  BE/app/src/main/java/com/issuetracker/app/AppApplication.java
  BE/app/src/main/resources/application.properties
  BE/app/src/test/java/com/issuetracker/app/AppApplicationTests.java
Labels: BE, chore, SPRINT#1

#11 [BE] feat/#9: 이슈 목록 반환 API 및 필터 기능 추가
  BE/app/build.gradle
  BE/app/src/main/java/com/issuetracker/app/AppApplication.java
  BE/app/src/main/java/com/issuetracker/app/issue/application/IssueService.java
  BE/app/src/main/java/com/issuetracker/app/issue/application/dto/IssueSearchData.java
  BE/app/src/main/java/com/issuetracker/app/issue/application/dto/IssueSearchInformation.java
  BE/app/src/main/java/com/issuetracker/app/issue/domain/Issue.java
  BE/app/src/main/java/com/issuetracker/app/issue/domain/IssueMapper.java
  BE/app/src/main/java/com/issuetracker/app/issue/ui/IssueController.java
  BE/app/src/main/java/com/issuetracker/app/issue/ui/dto/IssueSearchRequest.java
  BE/app/src/main/java/com/issuetracker/app/issue/ui/dto/IssueSearchResponse.java
  BE/app/src/main/java/com/issuetracker/app/issue/ui/dto/IssuesSearchResponse.java
  BE/app/src/main/java/com/issuetracker/app/label/application/dto/LabelSearchInformation.java
  BE/app/src/main/java/com/issuetracker/app/label/domain/Label.java
  BE/app/src/main/java/com/issuetracker/app/label/ui/dto/LabelSearchResponse.java
  BE/app/src/main/java/com/issuetracker/app/member/domain/Member.java
  BE/app/src/main/java/com/issuetracker/app/milestone/application/dto/MilestoneSearchInformation.java
  BE/app/src/main/java/com/issuetracker/app/milestone/domain/Milestone.java
  BE/app/src/main/java/com/issuetracker/app/milestone/ui/dto/MilestoneSearchResponse.java
  BE/app/src/main/resources/application.properties
  BE/app/src/main/resources/application.yml
  BE/app/src/main/resources/mapper/IssueMapper.xml
Labels: BE, feat, SPRINT#1

#13 [BE] feat/#12: 이슈 등록 API 일부 개발
  BE/app/src/main/java/com/issuetracker/app/issue/application/IssueService.java
  BE/app/src/main/java/com/issuetracker/app/issue/application/dto/IssueCreateData.java
  BE/app/src/main/java/com/issuetracker/app/issue/application/dto/IssueCreateInformation.java
  BE/app/src/main/java/com/issuetracker/app/issue/application/dto/IssueSearchData.java
  BE/app/src/main/java/com/issuetracker/app/issue/domain/Assignee.java
  BE/app/src/main/java/com/issuetracker/app/issue/domain/Issue.java
  BE/app/src/main/java/com/issuetracker/app/issue/domain/IssueLabelMapping.java
  BE/app/src/main/java/com/issuetracker/app/issue/domain/IssueSearch.java
  BE/app/src/main/java/com/issuetracker/app/issue/infrastrucure/AssigneeRepository.java
  BE/app/src/main/java/com/issuetracker/app/issue/infrastrucure/IssueLabelMappingRepository.java
  BE/app/src/main/java/com/issuetracker/app/issue/infrastrucure/IssueRepository.java
  BE/app/src/main/java/com/issuetracker/app/issue/ui/IssueController.java
  BE/app/src/main/java/com/issuetracker/app/issue/ui/dto/IssueCreateRequest.java
  BE/app/src/main/java/com/issuetracker/app/issue/ui/dto/IssueCreateResponse.java
  BE/app/src/main/java/com/issuetracker/app/label/domain/Label.java
  BE/app/src/main/java/com/issuetracker/app/member/domain/Member.java
  BE/app/src/main/java/com/issuetracker/app/milestone/domain/Milestone.java
  BE/app/src/main/resources/mapper/IssueMapper.xml
  BE/app/src/test/resources/schema.sql
Labels: BE, feat

#16 [FE] feat/#10: 1주차 컴포넌트 구현
  FE/src/components/Button/Button.tsx
  FE/src/components/Button/ButtonStyle.ts
  FE/src/components/DropdownIndicator/DropdownIndicator.tsx
  FE/src/components/FilterBar/FilterBar.tsx
  FE/src/components/Header/Header.tsx
  FE/src/components/Input/Input.tsx
  FE/src/components/IssueList/IssueList.tsx
Labels: FE, feat, SPRINT#1

#18 [FE] feat/#17: 이슈 목록 페이지 구현
  FE/src/App.tsx
  FE/src/pages/MainPage.tsx
Labels: FE, feat, SPRINT#1

#20 [FE] design/#19: 디자인 시스템 수정
  FE/src/styles/DesignSystem.ts
  FE/src/styles/GlobalStyles.ts
  FE/src/styles/base/Typo.ts
Labels: FE, design, SPRINT#1

#22 [FE] design/#21: 로고 및 사용자 이미지(샘플) 추가
  FE/public/logo/largeLogo.svg
  FE/public/logo/mediumLogo.svg
  FE/public/logo/profile.jpg
Labels: FE, design, SPRINT#1
